--- #projector(s) configuration file

#resolution of projectors, assumed to be the same for all of them
projector_resolution: [1024, 768]

#projector corner locations in world coordinates, structure [ TL, TR, BR, BL ] use y,x for each
#add new line for each projector
projector_coordinates: [[165.0,-27.0], [165.0,150.0], [0.0,126.0], [0.0,0.0]]


projector_locations: [('first', (100, 100, 500)), ('second', (-100, -100, 500))]

...

