--- #projector(s) configuration file

number_of_projectors: 2

#resolution of projectors, assumed to be the same for all of them
projector_resolution: [1024, 768]

#projector corner locations in world coordinates, structure [ TL, TR, BR, BL ] use y,x for each
#add new line for each projector
projector_coordinates: [[[133.0,-54.0], [133.0,102.0], [-6.0,148.0], [-11.0,-93.0]],
                        [[81.0,-78.0], [82.0,115.0], [-55.0,127.0], [-65.0,-83.0]]]


projector_locations: [['first', [18, 159, 235]], ['second', [24, -47, 230]]]


# camera configuration
# camera
sense_world_points: [[0,0,0],         [0, 100, 0],   [100, 100, 0], [100, 0, 0]]

sense_camera_points:  [[1.6,8.9,315], [1,-59.6,244], [102,-59.8,243], [99,8.6,308]]
...

