--- #projector(s) configuration file

number_of_projectors: 2

#resolution of projectors, assumed to be the same for all of them
projector_resolution: [1024, 768]

#projector corner locations in world coordinates, structure [ TL, TR, BR, BL ] use y,x for each
#add new line for each projector
projector_coordinates: [[[134.0,-61.0], [141.0,101.0], [-12.0,153.0], [-21.0,-101.0]],
                        [[88.0,-81.0], [91.5,121.0], [-66.0,138.0], [-70.0,-86.0]]]


projector_locations: [['first', [18, 159, 235]], ['second', [24, -47, 230]]]

#########################################
# camera configuration
# camera
sense_world_points: [[0,0,0],         [0, 100, 0],   [100, 100, 0], [100, 0, 0]]

sense_camera_points:  [[1.6,8.9,315], [1,-59.6,244], [102,-59.8,243], [99,8.6,308]]


#########################################
# simulator configuration

sim_world_perimeter: [[-100.0, -100.0], [-100.0, 100.0], [100.0, 100.0], [100.0, -100.0]]
sim_window_width: 400
sim_window_height: 400


...

