--- #projector(s) configuration file

number_of_projectors: 2

#resolution of projectors, assumed to be the same for all of them
projector_resolution: [1024, 768]

#projector corner locations in world coordinates, structure [ TL, TR, BR, BL ] use y,x for each
#add new line for each projector
projector_coordinates: [[[189.0,-70.0], [193.5,111.0], [46.0,129.0], [37.5,-75.0]],
                        [[47.5,-71.5], [56.0,130.0], [-99.0,131.0], [-105.0,-68.5]],
                        [[125.0,124.0], [-63.0,120.0], [-106.5,-62.0], [164.5,-57.0]]]


projector_locations: [['first', [18, 159, 235]], ['second', [24, -47, 230]], ['third', [125, 25, 230]]]

#########################################
# camera configuration
# camera
sense_world_points: [[0,0,0],         [0, 100, 0],   [100, 100, 0], [100, 0, 0]]

sense_camera_points:  [[1.6,8.9,315], [1,-59.6,244], [102,-59.8,243], [99,8.6,308]]


#########################################
# simulator configuration

sim_world_perimeter: [[-100.0, -100.0], [-100.0, 100.0], [100.0, 100.0], [100.0, -100.0]]
sim_window_width: 400
sim_window_height: 400


...

